config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: {
    sessions: 'users/sessions',
    passwords: 'users/passwords',
    registrations: 'users/registrations',
    confirmations: 'users/confirmations'

  }

  root 'home#index'

  get "detail", to: "home#detail"
  get "candidate/:id", to: "home#candidate", as: "candidate"
  get "drive/:id", to: "home#drive", as: "drive"
  post "fillform/:id", to: "home#fillform", as: "fillform"
  get "date/:data", to: "home#date", as: "date"
  get "way/:date", to: "home#way", as: "way"
  get "admin2/:id", to: "home#admin2", as: "admin2"
  post "admin3/:id", to: "home#admin3", as: "admin3"
  get "track/:id", to: "home#track", as: "track"
  get "result/:id", to: "home#result", as: "result"
  get "interinfo/:inter", to: "home#interinfo", as: "interinfo"
  get "update_user_data/:id", to: "home#update_user_data", as: "update_user_data"
  post "admin_update/:id", to: "home#admin_update", as: "admin_update"
  get "riview/:id", to: "home#riview", as: "riview"
  post "riview_update/:id", to: "home#riview_update", as: "riview_update" 
  get "create_drive", to: "home#create_drive", as: "create_drive"
  post "drive_save", to: "home#drive_save", as: "drive_save"
  get "drive_show/:id", to: "home#drive_show", as:"drive_show"
  get "access_date", to: "home#access_date", as: "access_date"
  get "name/:date", to: "home#name", as: "name"
  delete "candidate/:date",to: "home#deleter", as: "deleter"
  get "information", to: "home#information", as: "information"
  get "del/:id", to: "home#del", as: "del"
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  before_action :authenticate_user!, except: :index
  #skip_before_action :authenticate_user!, only: :index
  def index
    
  end

  def detail
    @a = User.all
    if flash[:redirect]=='1'
      redirect_to root_path
    end
  end

  def candidate 
    @candidates = User.find(params[:id])
  end

  def drive
    @drives = User.find(params[:id])
  end

  def fillform
    @drives = User.find_by(name: params[:name], email: params[:email])
    @date_data = Candidate.all
    if current_user.name == @drives.name && current_user.email == @drives.email
      if @date_data.find_by(date: params[:date], user_id: @drives.id)
        flash[:notice] = "You have already applied for this drive"
        redirect_to candidate_path
      else
        if @drives.candidates.create(date: params[:date]) && @drives.update(role: params[:role])
          flash[:notice]="your are registerd successfully"
          redirect_to candidate_path
        end
      end
    else
      flash[:notice] = "Wrong Information"
    end
  end

  def date
    @dates = Candidate.where(date: params[:data])
  end

  def admin2 
    @admin2 = User.find(params[:id])
  end

  def admin3
    # got params[:time] into time
    t=params.require(:user).permit(:time)
    str = t.inspect
    ar=str.split('"')
    time= ar[3]

    t=params.require(:user).permit(:inter)
    str = t.inspect
    ar=str.split('"')
    inter= ar[3]

    if time_checks_out(time,inter,params[:id])

     @update_admin = User.find(params[:id])
    if @update_admin.update(params.require(:user).permit(:name,:email,:passwords,:date,:admin_date,:inter,:time,:first,:second,:third))
      redirect_to access_date_path 
    else
      redirect_to admin2_path
    end
    else
      flash[:error]="Time is already taken"
      redirect_to admin2_path
    end
  end


  def track
    @track = User.find(params[:id])
  end

  def result
    @result = User.find(params[:id])
  end

  def interinfo
    if user_signed_in?
      @interinfo = User.where(inter: current_user.name)
    end
  end

  def update_user_data
    @update_user_datas = User.find(params[:id])
  end

  def admin_update
    @admin_update = User.find(params[:id])

    if @admin_update.update(params.require(:user).permit(:user_type))
      redirect_to detail_path
    else
      redirect_to update_user_data_path
    end
  end

  def riview
    @riview = User.find(params[:id])
  end

  def riview_update
    @riview_update = User.find(params[:id])

    if @riview_update.update(params.require(:user).permit(:riview))
      flash[:title]="review update successfully"
      redirect_to interinfo_path(@riview_update)
    else
      redirect_to riview_path
    end
  end

  def create_drive
    # @create_drive = Drive.new
  end

  def drive_save
    Drive.create(drive_date: params[:drive_date], role: params[:role])
    redirect_to access_date_path
  end

  def drive_show
    @drive_show = Drive.all
    candidate
  end

  def access_date
    @access_date = Candidate.all
  end

  def name
    @name = Candidate.where(date: params[:date])
  end

  def deleter
    @name = Candidate.where(date: params[:date])
    @name.each do|i|
      i.destroy
    end
    redirect_to access_date_path
  end 
  
  def information
    @information = Drive.all
  end

  def del
    @del = Drive.find(params[:id])
    @del.destroy
    redirect_to access_date_path
  end

  private
  
  def time_checks_out(t,s,n)
  condition = true
  num = User.find(n).time
  unless t.nil?
    #converts time string into int ex:- 6:30 to 630
    t=time_to_num(t)

    ar = User.where(inter:s).pluck(:time)
    ar.delete(num)
    ar.each do |i|
     unless i.nil?
        i2=time_to_num(i)
        
        if t.between?(i2,i2+100)
          condition = false
          break
       end
      end
    end
  end
  return condition
  end
  def time_to_num(t)
    ar2 = t.split(':')
    i2=ar2[0].to_i*100
    i2=i2+ar2[1].to_i
    return i2
  end

end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/home/access_date.html.erb
<% if user_signed_in? && current_user.user_type.upcase =="ADMIN"%>

  <%ar=[]%>
  <% @access_date.each do |i|%>
    <%unless ar.include? i.date%>
    <% ar.push(i.date) %> 
    <%end%>
  <%end%>

  <div class="container mt-3", style="width: 70rem;">
    <h3 class="text-danger">Welcome, <%= current_user.name.upcase%></h3>
    <table class="table table-striped table-bordered text-center bg-light">
      <tr>
        <th>Date of Drives</th>
        <th>Action</th>
      </tr>
      <% ar.each do |i|%>
        <tr>
          <td><%= link_to i, name_path(i)%></td>
          <td><button type="button" class="text-light btn btn-outline-danger"><%= link_to "Show",name_path(i)%></button>
          <button type="button" class="btn btn-outline-primary"><%= link_to "Destroy",deleter_path(i), data: {turbo_method: :delete ,turbo_confirm: "are you sure"}%></td></button>
        </tr>
      <%end%>
    </table>
    <h3><button type="button" class="btn btn-outline-info"><%= link_to "All_User_List", detail_path%></button></h3>
  <h3><%= link_to "Create Drive", create_drive_path, class: "text-danger"%></h3>
  <h3 class="btn btn-outline-info"><%= link_to "Show notice", information_path%></h3>
  </div>
  
<%end%>

app/views/home/admin2.html.erb
<% if user_signed_in? && current_user.user_type.upcase == 'ADMIN'%>
<div class="col-lg-6 mx-lg-auto card shadow mt-5">

    <div class="card-header">
    <h3 class="card-title text-center">Cadidate Details</h3>
   </div>
  <div class="card-body">
  <p class="text-white bg-dark text-center"><%=flash[:error]%></p>
  <%= form_with model: @admin2, method: :post, url: admin3_path(@admin2.id) do |form| %>
  
  
   <div class="form-group mb-2">
   <%= form.label :Name %><br>
    <%= form.text_field :name, class: "form-control form-control-lg"%>
  </div>
  
  <div class="form-group mb-2">
   <%= form.label :Email %><br>
   <%= form.text_field :email , class: "form-control form-control-lg"%>
  </div >

  <div class="form-group mb-2">
    <%= form.label :Role %><br>
    <%= form.text_field :role , class: "form-control form-control-lg"%>
   </div >
  
  
  <div class="form-group mb-2">
    <%= form.label :Interviewer %><br>
    <%= form.text_field :inter , class: "form-control form-control-lg"%>
  </div >

  <div class="form-group mb-2">
    <%= form.label :Set_date %><br>
    <%= form.text_field :admin_date , class: "form-control form-control-lg"%>
  </div >
  <%time = @admin2.time%>
  <div class="form-group mb-2">
    <%= form.label :Time %><br>
    <%=form.time_field :time,value:"#{time}",class: "form-control form-control-lg" %>
  </div >
  
  <div class="form-group mb-2">
    <%= form.label :First_Round %><br>
    <%= form.text_field :first , class: "form-control form-control-lg"%>
  </div >
   
  <div class="form-group mb-2">
    <%= form.label :Second_Round %><br>
    <%= form.text_field :second , class: "form-control form-control-lg"%>
  </div >
   
  <div class="form-group mb-2">
    <%= form.label :Third_Round %><br>
    <%= form.text_field :third , class: "form-control form-control-lg"%>
  </div >
  
  <div>
   <%= form.submit "update", class: "btn btn-primary btn-lg"  %>
  </div>
  <% end %>
  
  </div>
  </div>
<%end%>

app/views/home/candidate.html.erb
<%if user_signed_in?%>
  <h3 class="text-danger">Welcome-</h3><br>
  <div class="card border-primary mb-3" style="max-width: 18rem;">
    <div class="card-header text-center"><h3>Your Details</h3></div>
    <div class="card-body text-primary">
      <p class="text-success">
      <h5 class="card-title">Name:<p class="text-danger"><%= @candidates.name%><br></p></h5>
      <h5 class="card-title">Email:<p class="text-danger"><%= @candidates.email%><br></p></h5>
      
      <p class="card-text"></p>
      <button type="button" class="btn btn-outline-dark"><%= link_to "Aply for drive", drive_path(@candidates.id)%></button>
      <button type="button" class="btn btn-outline-success mt-2"><%= link_to "track your drive status", track_path(@candidates.id)%></button>
      <button type="button" class="btn btn-outline-danger mt-2"><%= link_to "Result", result_path(@candidates.id)%></button>
      <button type="button" class="btn btn-outline-danger mt-2"><%= link_to "all Drives", drive_show_path(@candidates)%></button>
    </div>
  </div>
<%end%>

app/views/home/date.html.erb
<%if @dates && user_signed_in? && current_user.user_type.upcase == 'ADMIN'%>

  <% @dates.each do |i|%>
  <% @a = User.find(i.user_id)%>
   <%= link_to @a.name, admin2_path(@a.id)%>
  <%end%>

<%end%>

app/views/home/drive.html.erb
<br>
<div class="col-lg-6 mx-lg-auto card shadow mt-5">

     <div class="card-header">
      <h3 class="card-title text-center">Apply for drive</h3>
    </div>
  <div class="card-body">
    <%=notice%>
<%= form_with method: :post, url:fillform_path(@drives.id)  do |form| %>

  <div class="form-group mb-2">
    <%= form.label :name %><br>
    <%= form.text_field :name, placeholder: "Enter your name" ,class: "form-control form-control-lg"  %>
  </div>

  <div class="form-group mb-2">
    <%= form.label :email %><br>
     <%= form.email_field :email,  placeholder: "Enter your email" ,class: "form-control form-control-lg"%>
  </div>

  <div class="form-group mb-2">
    <%= form.label :Role %><br>
     <%= form.text_field :role,  placeholder: "Enter your role" ,class: "form-control form-control-lg"%>
  </div>

  

  <div class="form-group mb-2">
    <%= form.label :date %><br>
    <%= form.date_field :date , class: "form-control form-control-lg"%>
  </div >

  <div>
    <%= form.submit "Submit", class: "btn btn-primary btn-lg"  %>
  </div>
<% end %>
</div>
</div>

app/views/home/drive_show.html.erb
<% if user_signed_in?%>
  <div class="container mt-3", style="width: 70rem;">
    <h3 class="text-danger">Welcome, <%= current_user.name.upcase%></h3>
    <table class="table table-striped table-bordered text-center bg-light">
      <tr>
        <th>Date of Drives</th>
        <th>Role</th>
      </tr>
      <% @drive_show.each do |i|%>
        <tr>
          <td><%= i.drive_date%></td>
          <td><%= i.role%></td>
        </tr>
      <%end%>
      <h6><button type="button" class="btn btn-sm btn-outline-danger"><%= link_to "Aply for drive", drive_path(@candidates)%>
      </button></h6>
    </table>
  </div>
<%end%>

app/views/home/index.html.erb
<h1 class="text-danger text-center">Welcome to MYWEB for interview</h1>
<!-- <table class="text-center table table-striped">
    <tr>
    <th><h2>Date of drives</h2></th>
    </tr>
    <tr>
      <td class="text-danger"><%= link_to "12-08-2022"%></td>  
    </tr>
    <tr>
      <td class="text-danger"><%= link_to "13-08-2022"%></td>
    </tr>
    <tr>
      <td class="text-danger"><%= link_to "14-08-2022"%></td>
    </tr>
  </table> -->

app/views/home/information.html.erb
<% @information.each do |i|%>
  <%= i.drive_date%>
  <%= i.role%>
  <%= link_to "Destroy",del_path(i)%>
  <hr>
<%end%>

<div class="container mt-3", style="width: 70rem;">
  <h3 class="text-danger">Welcome, <%= current_user.name.upcase%></h3>
  <table class="table table-striped table-bordered text-center bg-light">
    <tr>
      <th>Date of Drives</th>
      <th>Role</th>
      <th>Action</th>
    </tr>
    <% @information.each do |i|%>
      <tr>
        <td><%= i.drive_date%></td>
        <td><%= i.role%></td>
        <td><button type="button" class="btn btn-outline-primary"><%= link_to "Destroy",del_path(i)%></td></button>
      </tr>
    <%end%>
  </table>
</div>
  

app/views/home/interinfo.html.erb
<% if user_signed_in? && current_user.user_type.upcase == 'INTER'%>
  <p class="text-danger">Welcome <%= current_user.name.upcase%></p>
<table class="text-center table table-striped">
  <p class="text-success"><%= flash[:title]%></p>
  <tr>
  <th>Candidate Name</th>
  <th>Date</th>
  <th>Time</th>
  <th>Riview</th>
  </tr>
  
  <% @interinfo.each do |f|%>
  <tr>
    <td class="text-danger"><%= f.name%></td> 
    <td class="text-success"><%= f.admin_date%></td>
    <td class="text-primary"><%= f.time%></td>
    <td class="text-primary"><%= link_to "Give Riview", riview_path(f)%></td>
    
  </tr>
  <%end%>
  
</table>
<%end%>

app/views/home/myadd.html.erb
Name:<p class="text-danger"><%= @track.name%></p>
Email<p class="text-danger"><%= @track.email%></p>
Interviewer Name<p class="text-danger"><%= @track.inter%></p>
Time of Interview<p class="text-danger"><%= @track.time%></p>

app/views/home/name.html.erb
<% if user_signed_in? && current_user.user_type.upcase == "ADMIN"%>
  <% @name.each do |i|%>
  <% @a = User.find(i.user_id)%>
    <%= link_to @a.name, admin2_path(@a.id)%><br>
  <%end%>
  <h6><button type="button" class="btn btn-secondary"><%= link_to "Back", access_date_path%></button></h6>
<%end%>

app/views/home/riview.html.erb
  
  <% if user_signed_in? && current_user.user_type.upcase == 'INTER'%>
  <div class="col-lg-6 mx-lg-auto card shadow mt-5">
  
      <div class="card-header">
      <h3 class="card-title text-center">Riview</h3>
     </div>
    <div class="card-body">
    <p class="text-white bg-dark text-center"><%=flash[:error]%></p>
    <%= form_with model: @riview, method: :post, url: riview_update_path(@riview.id) do |form| %>
    
    <div class="form-group mb-2">
     <%= form.label :Name %><br>
      <%= form.text_field :name, class: "form-control form-control-lg"%>
    </div>

    <div class="form-group mb-2">
      <%= form.label :Riview %><br>
      <%= form.text_field :riview , class: "form-control form-control-lg"%>
    </div >
    
    <div>
     <%= form.submit "update", class: "btn btn-primary btn-lg"  %>
    </div>
    <% end %>
    
    </div>
    </div>
  <%end%>

app/views/home/track.html.erb
<% if user_signed_in?%>
Name:<p class="text-danger"><%= @track.name%></p>
Email:<p class="text-danger"><%= @track.email%></p>
<!-- Interviewer Name:<p class="text-danger"><%= @track.inter%></p> -->
Date of Interview:<p class="text-danger"><%= @track.admin_date%></p>
Time of Interview:<p class="text-danger"><%= @track.time%></p>
<%end%>

app/views/home/update_user_data.html.erb
  
  <% if user_signed_in? && current_user.user_type.upcase == 'ADMIN'%>
  <div class="col-lg-6 mx-lg-auto card shadow mt-5">
  
      <div class="card-header">
      <h3 class="card-title text-center">User Details</h3>
     </div>
    <div class="card-body">
    <p class="text-white bg-dark text-center"><%=flash[:error]%></p>
    <%= form_with model: @update_user_datas, method: :post, url: admin_update_path(@update_user_datas.id) do |form| %>
    
    
     <div class="form-group mb-2">
     <%= form.label :Name %><br>
      <%= form.text_field :name, class: "form-control form-control-lg"%>
    </div>

    <div class="form-group mb-2">
      <%= form.label :user_type %><br>
      <%= form.text_field :user_type , class: "form-control form-control-lg"%>
    </div >
    
    <div>
     <%= form.submit "update", class: "btn btn-primary btn-lg"  %>
    </div>
    <% end %>
    
    </div>
    </div>
  <%end%>